default: &default

development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  socket: /var/lib/mysql/mysql.sock
  database: baukis_development

test:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  socket: /var/lib/mysql/mysql.sock
  database: baukis_test


production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: postgres://pwmogzvbbnskyp:bqxcYo3fkyZcozBmdXHzYpMfFi@ec2-54-204-31-33.compute-1.amazonaws.com:5432/d6s9p64qm6o60r
