# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0199745add377b12db73b9b32f4a0561bf21074e269c7a7b5c8bb8dbc3c2dddc5fd45189ed6ab7751f6219a4a9f96532b605bff8da9faa723d8b1b744d463c26

test:
  secret_key_base: 1ac75af8a859733e559e26eec77fa539ebbf9455fdad867b38b7e5d9823fc6b3db5f35de3ba1e4ff801ff8ba8c2b3e4fdcb135027cd2078251e444e310cfb78b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
